name: font_awesome_svg_icons
description: A Flutter package for generating Font Awesome icons as SVG images, with support for duotone icons.
maintainer: Andreas Wiig (@wiigolas)
version: 1.0.0
homepage: https://github.com/wiigolas/font_awesome_svg_icons
repository: https://github.com/wiigolas/font_awesome_svg_icons.git

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_lints: ^2.0.1
  dependency_validator: ^3.2.2
  flutter_test:
    sdk: flutter
  recase: ^4.1.0
